// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQL1EdE7aEwRJh2SjaVsIz5XDCi-sIm4Q',
    appId: '1:771163168949:web:c8b7bca16d97b0a500defc',
    messagingSenderId: '771163168949',
    projectId: 'hicampus-acd31',
    authDomain: 'hicampus-acd31.firebaseapp.com',
    storageBucket: 'hicampus-acd31.firebasestorage.app',
    measurementId: 'G-N7RZT8Z2XN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsc5Z7wBW6QqdwVb9OgSonsPU2hPBhH-4',
    appId: '1:771163168949:android:c38589b42d47c1f300defc',
    messagingSenderId: '771163168949',
    projectId: 'hicampus-acd31',
    storageBucket: 'hicampus-acd31.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuKZ1uECQLpuox_jjTNYfAezpfF1rwiLI',
    appId: '1:771163168949:ios:5eeccd3f3c84a4e200defc',
    messagingSenderId: '771163168949',
    projectId: 'hicampus-acd31',
    storageBucket: 'hicampus-acd31.firebasestorage.app',
    iosBundleId: 'com.kmu186.hicampus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQL1EdE7aEwRJh2SjaVsIz5XDCi-sIm4Q',
    appId: '1:771163168949:web:42887cfdd1a8ede000defc',
    messagingSenderId: '771163168949',
    projectId: 'hicampus-acd31',
    authDomain: 'hicampus-acd31.firebaseapp.com',
    storageBucket: 'hicampus-acd31.firebasestorage.app',
    measurementId: 'G-RL4MX4LWQJ',
  );
}
